################################################################################
# default                                                                      #
# everything that is starting with disallow uses permission, if value is true  #
# possible message variables  %user, %server, %core                            #
# possible timemessage variables %time                                         #
################################################################################
#
###########
# Message #
###########
enable-Messages: true
message: Welcome %user on %server running on %core !
firstjoin:  It's the first time
leftmessage: Player %user left %server
timemessage: It's %time
whitelist-message: You aren't whitelisted on this server
banmessage: You are a Bunny! You got banned from this server
serverfullmessage: I'm sorry! The Server is full!
maintenance_message: Server is under construction
maintenance_mode: false
#
#########################
# Commandlogger enable  #
#########################
commandLogger: true
#
##############################################
# timezone gmt 0 london , gmt+2 Berlin , etc #
##############################################
timezone: 2
##################
# World-Settings #
##################
disallowbuild: true
disablebreak: true
Blockcreeper: true
prevent-tnt: true
Blockender: true
xpsave: true
prevent-fire-spread: true
prevent-lava-spread: true
general-spread: true
flint-and-steal-spread: true
strike-spread: true
#
#################
# Plugin Advert #
#################
plugin-advert: true
###################
# Time in seconds #
# 60 == 1 min     #
###################
#
time-between-adverts: 300
advert-message: Our hompage www.SmartServerTool.de
#
##############
# Item-Drops #
##############
leave-drop-rate: 4
diamond-drop-rate: 3
normal-frop-rate: 1
glass-sand-drop: true
glasspane-drop: true
diamond-ore-drop: true
golden-apple-drop: true