name: MyOwn
version: 0.3
main: com.github.ysl3000.MyOwn
commands:
 admin:
  usage: /admin
  description: Toggle OP
  permission: MyOwn.admin
  permission-message: You don't have MyOwn.admin
 gmc:
  usage: /gmc
  description: Set Creative
  permission: MyOwn.gmc
  permission-message: You don't have MyOwn.gmc
 gms:
  usage: /gms
  description: Set Survival
  permission: MyOwn.gms
  permission-message: You don't have MyOwn.gmc
 gm:
  usage: /gm
  description: Current GameMode
  permission: MyOwn.gm
  permission-message: You don't have MyOwn.gm
 td:
  usage: /td
  description: set Time to Day
  permission: MyOwn.td
  permission-message: You don't have MyOwn.td
 tn:
  usage: /tn
  description: set Time to Night
  permission: MyOwn.tn
  permission-message: You don't have MyOwn.tn
 sun:
  usage: /sun
  description: Set Sun
  permission: MyOwn.sun
  permission-message: You don't have MyOwn.sun
 storm:
  usage: /storm
  description: Set Storm
  permission: MyOwn.storm
  permission-message: You don't have MyOwn.storm
 wg:
  usage: /wg
  description: get Weather
  permission: MyOwn.wg
  permission-message: YYou don't have MyOwn.wg
 
 